# Generated by Django 2.1.7 on 2019-12-09 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyhq', '0002_auto_20191205_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='uploaded',
            new_name='downloaded',
        ),
        migrations.RemoveField(
            model_name='validationpassword',
            name='hash_digest',
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='order',
            name='waiver',
        ),
    ]
