# Generated by Django 2.1.7 on 2020-01-07 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyhq', '0003_auto_20191209_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationpassword',
            name='uploaded_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
